sudo: required

language: generic

services:
  - docker

install:
  - docker build -t mountainlab-js-test .

script:
  - docker run mountainlab-js-test

notifications:
  email:
    recipients:
      - jmagland@flatironinstitute.org
    on_success: change # default: change
    on_failure: always # default: always